server:
  port: 8081
spring:

  rabbitmq:
    host: 47.93.50.114
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloud?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jinshuai
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:

  # 引入映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志在控制台显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
